### ISSUE TITLE
求更新适配最新版 wafer

### ISSUE THREAD

**Issue by libingtong** [jmluang/weappLogin-for-laravel#1]

**Comment by jmluang** [comment]
wafer并没有更新

**Comment by libingtong** [comment]
这是新 Wafer2 JS SDK里的方法loginWithCode

**Comment by libingtong** [comment]
而如果使用 js-sdk下的 JS 登录的话，X-WX-Skey 又有问题了
<img width="632" alt="wx20181222-145820 2x" src="https://user-images.githubusercontent.com/2126613/50371659-26a7ba00-05fa-11e9-92e7-367c571a212c.png">

**Comment by jmluang** [comment]
能否提供代码片段，未这里没啥问题
![1](https://user-images.githubusercontent.com/11557732/50374413-ce3be100-0628-11e9-8200-7b1c70956f37.png)

**Comment by jmluang** [comment]
或者上传这个

![2018-12-22 8 36 39](https://user-images.githubusercontent.com/11557732/50374438-76ea4080-0629-11e9-8a05-2c4c6582e073.png)
